# Generated by Django 3.2.7 on 2021-11-23 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0003_personasoporte_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personasoporte',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
